#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     accel,          sensorI2CCustom)
#pragma config(Sensor, S4,     IR,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    A,                    tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    B,                    tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "utils.swoll.h"

int pitch = 0; // x-axis
int bank = 0; // y-axis
int z = 0; // z-axis
bool one = true; // while toggle boolean
string _tmp;


task main()
{
	eraseDisplay();
	motor[Left] = 50;
	motor[Right] = 50;
	wait1Msec(1500);
	motor[Left] = 0;
	motor[Right] = 0;
	while(one)
	{
		//eraseDisplay();
		HTACreadAllAxes(accel, pitch, bank, z);
		nxtDisplayTextLine(2, "   X    Y    Z");
		StringFormat(_tmp, "%4d %4d", pitch, bank);
		nxtDisplayTextLine(3, "%s %4d", _tmp, z);
		if (pitch <= -19 || pitch >= 19)
		{
			motor[Left] = 15;
			motor[Right] = 20;	// >=19 works
		}
		else
		{
			motor[Left] = 50;
			motor[Right] = 50;
			wait1Msec(300);
			motor[Left] =0;
			motor[Right] = 0;
			one = false;
		}
	}
}
