#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     accel,          sensorI2CCustom)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "utils.swoll.h"

int pitch = 0; // x-axis
int bank = 0; // y-axis
int z = 0; // z-axis
bool one = true; // while toggle boolean
string _tmp;


task main()
{
	eraseDisplay();
	motor[Left] = 50;
	motor[Right] = 50;
	wait1Msec(1200);
	motor[Left] = 0;
	motor[Right] = 0;
	while(one)
	{
		//eraseDisplay();
		HTACreadAllAxes(accel, pitch, bank, z);
		nxtDisplayTextLine(2, "   X    Y    Z");
		StringFormat(_tmp, "%4d %4d", pitch, bank);
		nxtDisplayTextLine(3, "%s %4d", _tmp, z);
		/*if (pitch <= -15)
		{
			motor[Left] = 15;
			motor[Right] = 20;
		}
		else if (pitch >= 15)		// >=15 works 80% of the time
		{
			motor[Left] =0;
			motor[Right] = 0;
			one = false;
		}*/
		////////////////////////////		Test Stuff
		motor[Left] = abs(pitch);
		motor[Right] = abs(pitch);
		if (pitch >= -20 && pitch <= 20)
		{
			motor[Left] = 0;
			motor[Right] = 0;
			one = false;
		}
		////////////////////////////
	}
}
