#pragma config(Sensor, S1,     colour,         sensorI2CHiTechnicColor)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "/drivers/hitechnic-colour-v1.h"

task main()
{
	eraseDisplay();
	int x;
	int y;
	int z;
	while(true)
	{
		x = HTCSreadColor(colour);
		nxtDisplayString( 1, "%d", x);
		nxtDisplayString( 2, "%d", y);
		nxtDisplayString( 3, "%d", z);
		wait1Msec(100);
	}
}
