#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     accel,          sensorI2CCustom)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "utils.swoll.h"

task main()
{
	while(true)
	{
		initializeRobot();
		SetTurnTarget(-83.5);			//good target	83.5
		while(g_turnEnabled) // Turn the robot Perp
		{
			GyroTask(g_Gyro);
			TurnTask();
			wait1Msec(10);
		}
		wait1Msec(1000);
	}
}
