#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     accel,          sensorI2CCustom)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorg,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     Sweep,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    A,                    tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    B,                    tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    Bar,                  tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_5,    C,                    tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-irseeker-v2.h"
#include "utils.swoll.h"

int ding;
bool matt = true;

task main()
{
	servo[A] = 155;
	servo[B] = 110;
	servo[C] = 255;
	/*wait1Msec(300);
	//motor[Lift] = 50;
	wait1Msec(300);
	motor[Lift] = 0;
	servo[Bar] = 0;
	wait1Msec(1000);
	servo[Bar] = 128;
	deRive(2000);*/
	while (matt)
	{
		ding = SensorValue[IR];
		wait1Msec(300);
		ding = SensorValue[IR];
		wait1Msec(300);
		ding = SensorValue[IR];
		if (ding == 0)		// Thing is facing us
		{
			PlaySound(soundBeepBeep);
			wait1Msec(500);
			//matt = false;
			motor[Left] = 0;
			motor[Right] = 0;
			/*deRive(500);
			turner(-25);
			deRive(2200);
			turner(97.5);
			deRive(3000);*/
		}
		else if (ding == 4 || ding == 3)		// Thing is at 45
		{
			PlaySound(soundUpwardTones);
			wait1Msec(500);
			//matt = false;
			motor[Left] = 0;
			motor[Right] = 0;
			//deRive(2000);
			//turner(40);
			//deRive(2000);
		}
		else if (ding == 5)		// Thing is could be 90 or 45
		{
			PlaySound(soundDownwardTones);
			wait1Msec(500);
			//matt = false;
			motor[Left] = 0;
			motor[Right] = 0;
		}
	}
}
