#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     R,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     L,             tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     F,             tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     B,             tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c";
#include "utils.omni.h"

task main()			// Motor F between bat and mtr controller
{
	initializeRobot();
	while(true)
	{
		getJoystickSettings(joystick);
		if (abs(joystick.joy1_x2) < 20)
		{
			motor[F] = joystick.joy1_x1;
			motor[R] = joystick.joy1_y1;
			motor[L] = joystick.joy1_y1;
			motor[B] = joystick.joy1_x1;
		}
		else if (abs(joystick.joy1_x1) < 20 && abs(joystick.joy1_y2) < 20 && abs(joystick.joy1_y1) < 20)
		{
			motor[F] = -joystick.joy1_x2;
			motor[R] = joystick.joy1_x2;
			motor[L] = -joystick.joy1_x2;
			motor[B] = joystick.joy1_x2;
		}
		else
		{
			motor[F] = 0;
			motor[R] = 0;
			motor[L] = 0;
			motor[B] = 0;
		}
	}
}
