#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     accel,          sensorI2CCustom)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorg,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     Sweep,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    A,                    tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    B,                    tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    Bar,                  tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_5,    C,                    tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////
///////////////////////////////////
///			Last Edit: Armon	10/23 ///
///////////////////////////////////
///////////////////////////////////


//#include "drivers/hitechnic-sensormux.h"
//#include "drivers/lego-ultrasound.h"
#include "drivers/hitechnic-irseeker-v2.h"

//const tMUXSensor sonar1 = msensor_S4_1;
//const tMUXSensor sonar2 = msensor_S4_2;
//const tMUXSensor IR = msensor_S4_3;

#include "utils.swoll.h"

bool one = true; // while toggle boolean

task main()
{
	waitForStart();
	servo[A] = 155;
	servo[B] = 110;
	servo[C] = 255;
	servo[Bar] = 128;
	motor[Lift] = 50;
	wait1Msec(300);
	motor[Lift] = 0;
	int pitch = 0; // x-axis
	int bank = 0; // y-axis
	int z = 0; // z-axis
	string _tmp;
	eraseDisplay();
	motor[Left] = -50;
	motor[Right] = -60;
	wait1Msec(1500);
	motor[Left] = 0;
	motor[Right] = 0;
	while(one)
	{
		deRive(-2500);
		nMotorEncoder[Right] = 0;
		motor[Left] = -2;
		motor[Right] = -70;
		wait1Msec(500);
		motor[Left] =0;
		motor[Right] = 0;
		one = false;
		//}
		//}
		one = true;
		//turner(-180);	// Turn 1		-83.5
		deRive(-2700);			//2900`	//-4000
		wait1Msec(100);
		servo[A] = 0;
		servo[B] = 255;
		wait1Msec(400);
		motor[Lift] = 100;			/// Keep this
		wait1Msec(1000);
		motor[Lift] = 0;
		wait1Msec(500);					/// Keep this
		deRive(-nMotorEncoder[Right]);
		deRive(600);
		turner(83.5);
		deRive(1500);
		turner(100);
		deRive(-7800);
		servo[A] = 240;
		servo[B] = 0;
		one = false;
	}
}
