#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     accel,          sensorI2CCustom)
#pragma config(Motor,  motorA,          LA,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          LB,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     Right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Left,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     Lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     Flap,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "utils.swoll.h"
#include "JoystickDriver.c"

task main()
{
	while (true)
	{
		Drive(Left, Right);
		if (joy1Btn(6))
		{
			motor[Lift] = 100;
		}
		else if (joy1Btn(8))
		{
			motor[Lift] = -100;
		}
		else
		{
			motor[Lift] = 0;
		}
		if (joy1Btn(5))
		{
			motor[Flap] = 100;
		}
		else if (joy1Btn(7))
		{
			motor[Flap] = -100;
		}
		else
		{
			motor[Flap] = 0;
		}
		if (joy1Btn(2))
		{
			motor[LA] = 100;
			motor[LB] = 100;
		}
		else if (joy1Btn(4))
		{
			motor[LA] = -100;
			motor[LB] = -100;
		}
		else
		{
			motor[LA] = 0;
			motor[LB] = 0;
		}
	}
}
