#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     accel,          sensorI2CCustom)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     Right,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Flap,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     Left,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Lift,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    Tube1,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    Tube2,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "utils.swoll.h"
#include "JoystickDriver.c"

task main()
{
	while (true)
	{
		Drive(Left, Right);

		if (joy1Btn(6))
		{
			motor[Lift] = 100;
		}
		else if (joy1Btn(8))
		{
			motor[Lift] = -100;
		}
		else
		{
			motor[Lift] = 0;
		}

		if (joy1Btn(5))
		{
			motor[Flap] = 100;
		}
		else if (joy1Btn(7))
		{
			motor[Flap] = -100;
		}
		else
		{
			motor[Flap] = 0;
		}

		if (joy1Btn(6))
		{
			servo[Tube1] = 155;		// Both servos up
			servo[Tube2] = 110;
		}
		else if (joy1Btn(8))
		{
			servo[Tube1] = 0;			// Both servos down
			servo[Tube2] = 255;
		}
	}
}
