#pragma config(Sensor, S1,     HTRCX,               sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * $Id: hitechnic-irlink-rcx-test1.c 109 2012-09-25 17:10:26Z xander $
 */

/**
 * hitechnic-irlink-rcx.h provides an API for the HiTechnic IR Link Sensor to allow
 * communication between the NXT and RCX.
 *
 * Changelog:
 * - 0.1: Initial release
 *
 * Credits:
 * - Big thanks to HiTechnic for providing me with the hardware necessary to write and test this.
 * - Big thanks to Thorsten Benter for giving me one of his RCXs to work with!
 *
 * License: You may use this code as you wish, provided you give credit where it's due.
 *
 * THIS CODE WILL ONLY WORK WITH ROBOTC VERSION 3.51 AND HIGHER.
 * Xander Soldaat (mightor_at_gmail.com)
 * 16 September 2010
 * version 0.1
 */

#include "drivers/hitechnic-irlink-rcx.h"

task main () {
  short msg = 0x00FD;
  eraseDisplay();
  nxtDisplayTextLine(6, "Press [enter]");
  nxtDisplayTextLine(7, "to send msg");
  while(true) {
    // Increment the msg
    msg++;
    while(nNxtButtonPressed != kEnterButton) EndTimeSlice();
    while(nNxtButtonPressed != kNoButton) EndTimeSlice();
    // Send the message to the RCX and display
    PlaySound(soundBlip);
    nxtDisplayCenteredBigTextLine(2, "0x%04X", msg);
    HTRCXsendWord(HTRCX, msg);
  }
}

/*
 * $Id: hitechnic-irlink-rcx-test1.c 109 2012-09-25 17:10:26Z xander $
 */
