#pragma config(Sensor, S1,     MSIMU,                sensorI2CCustomFastSkipStates)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * $Id: mindsensors-imu-test1.c 109 2012-09-25 17:10:26Z xander $
 */

/**
 * mindsensors-imu.h provides an API for the Mindsensors AbsoluteIMU Sensor.  This program
 * demonstrates how to use that API.
 *
 * Changelog:
 * - 0.1: Initial release
 *
 * Credits:
 * - Big thanks to Mindsensors for providing me with the hardware necessary to write and test this.
 *
 * License: You may use this code as you wish, provided you give credit where it's due.
 *
 * THIS CODE WILL ONLY WORK WITH ROBOTC VERSION 3.51 AND HIGHER.
 * Xander Soldaat (mightor_at_gmail.com)
 * 25 August 2012
 * version 0.1
 */

#include "drivers/mindsensors-imu.h"

task main(){

  int x_val, y_val, z_val;      // axis values

  nxtDisplayCenteredTextLine(0, "Mindsensors");
  nxtDisplayCenteredBigTextLine(1, "IMU");
  nxtDisplayCenteredTextLine(3, "Test 1");
  nxtDisplayCenteredTextLine(5, "Connect sensor");
  nxtDisplayCenteredTextLine(6, "to S1");
  wait1Msec(2000);
  eraseDisplay();

  while (true){

		// Read the GYROSCOPE
    // There are 3 ways to do this:

    // All at once, very convenient if you need all 3
    MSIMUreadGyroAxes(MSIMU, x_val, y_val, z_val);

    // Via a single command with the axis specified as one of the arguments
		//x_val = MSIMUreadGyroAxis(MSIMU, MSIMU_GYRO_X_AXIS);    // Get x-axis in dps.
		//y_val = MSIMUreadGyroAxis(MSIMU, MSIMU_GYRO_Y_AXIS);    // Get y-axis in dps.
		//z_val = MSIMUreadGyroAxis(MSIMU, MSIMU_GYRO_Z_AXIS);    // Get z-axis in dps.

    // Using a macro that calls the above function with the right argument
    // x_val = MSIMUreadGyroXAxis(MSIMU);    // Get x-axis in dps.
		// y_val = MSIMUreadGyroYAxis(MSIMU);    // Get y-axis in dps.
		// z_val = MSIMUreadGyroZAxis(MSIMU);    // Get z-axis in dps.

		nxtDisplayTextLine(1, "%d", x_val);
		nxtDisplayTextLine(2, "%d", y_val);
		nxtDisplayTextLine(3, "%d", z_val);

		// Read the accelerometer
		// Again, there are multiple ways to do this:

		// All at once
		MSIMUreadAccelAxes(MSIMU, x_val, y_val, z_val);

		// One by one, specifying the axis as an argument
		// x_val = MSIMUreadAccelAxis(MSIMU, MSIMU_ACC_X_AXIS);
		// y_val = MSIMUreadAccelAxis(MSIMU, MSIMU_ACC_Y_AXIS);
		// z_val = MSIMUreadAccelAxis(MSIMU, MSIMU_ACC_Z_AXIS);

		// Function that doesn't require a specified axis, this is just a macro
		// x_val = MSIMUreadAccelXAxis(MSIMU);
    // y_val = MSIMUreadAccelYAxis(MSIMU);
    // z_val = MSIMUreadAccelZAxis(MSIMU);

		nxtDisplayTextLine(5, "%d", x_val);
		nxtDisplayTextLine(6, "%d", y_val);
		nxtDisplayTextLine(7, "%d", z_val);
		wait1Msec(50);
  }
}

/*
 * $Id: mindsensors-imu-test1.c 109 2012-09-25 17:10:26Z xander $
 */
